/**
 * Typed access to the generated design system catalog.
 *
 * Regenerate with `npm run ds:catalog` whenever the design system moves.
 * This module is safe to import from client components: it holds no answers,
 * only the list of components that exist.
 */
import catalog from '@/content/ds-catalog.json'

export type DsStorybook = {
  title: string
  docsId: string
  /** The deep link to this component's documentation page. */
  url: string
}

export type DsComponent = {
  name: string
  slug: string
  category: string
  /** Where the component is documented. `specs` alone means no Storybook story. */
  source: 'specs' | 'storybook' | 'both'
  selectors: string[]
  cssClasses: string[]
  modifiers: string[]
  specPath: string | null
  /** Null when the component has no story — which is itself the "not living" flag. */
  storybook: DsStorybook | null
  intents: string[]
  /** Components genuinely easy to mistake for this one — the best distractors. */
  confusableWith: string[]
}

export const DS_CHECKSUM: string = catalog.checksum
export const DS_CATEGORIES: readonly string[] = catalog.categories
// TypeScript widens `source` to `string` when importing JSON, so the union has to be
// asserted. The file is generated by `npm run ds:catalog` from this very type, and
// `npm test` parses a sample through the schema, so the assertion is checked rather
// than merely asserted.
export const DS_COMPONENTS = catalog.components as readonly DsComponent[]

const byName = new Map(DS_COMPONENTS.map((component) => [component.name, component]))

export function isKnownComponent(name: string): boolean {
  return byName.has(name)
}

export function getComponent(name: string): DsComponent | null {
  return byName.get(name) ?? null
}

export function componentsInCategory(category: string): DsComponent[] {
  return DS_COMPONENTS.filter((component) => component.category === category)
}

/**
 * The deep link to a component's Storybook page, or null when it has none.
 *
 * A URL is not an answer, so this is safe to call from a client component — which
 * is what lets the admin form fill the documentation field as you pick a component.
 */
export function docUrlFor(name: string): string | null {
  return getComponent(name)?.storybook?.url ?? null
}

/**
 * Whether the design system still publishes this component.
 *
 * Thirteen catalog entries have a spec but no Storybook story; ten of them the
 * design-guidelines plugin has already deleted as no longer part of the documented
 * system. Writing a question about one of those is probably a mistake, so the admin
 * warns — without blocking, because existing questions name several of them.
 */
export function hasLivingStory(name: string): boolean {
  return getComponent(name)?.storybook != null
}

/**
 * Plausible wrong answers for a question whose answer is `answer`.
 *
 * Ranked by how convincing the mistake would be: components curated as genuinely
 * confusable come first, then the rest of the answer's own category, then anything
 * else. The last tier only ever gets used because some categories are too small to
 * fill a 6-option hard question on their own — `actions` holds 5 components total.
 *
 * Deterministic on purpose: pressing the button twice gives the same three
 * suggestions, which are the best three rather than a fresh sample.
 */
export function suggestDistractors(answer: string, count = 3, exclude: string[] = []): string[] {
  const target = getComponent(answer)
  if (!target) return []

  const skip = new Set([answer, ...exclude])
  const tierOf = (component: DsComponent): number => {
    const confusable = target.confusableWith.includes(component.name)
    const sameCategory = component.category === target.category
    if (confusable && sameCategory) return 0
    if (confusable) return 1
    if (sameCategory) return 2
    return 3
  }

  return DS_COMPONENTS.filter((component) => !skip.has(component.name))
    .map((component) => ({ component, tier: tierOf(component) }))
    .sort((a, b) => a.tier - b.tier || a.component.name.localeCompare(b.component.name))
    .slice(0, count)
    .map(({ component }) => component.name)
}

/**
 * How many distractors the answer's own category can supply. The admin form uses
 * this to say so up front rather than silently returning too few suggestions.
 */
export function distractorsAvailableInCategory(answer: string): number {
  const target = getComponent(answer)
  if (!target) return 0
  return componentsInCategory(target.category).length - 1
}
