/**
 * Concatenates the migrations into one file to paste into the Supabase SQL editor.
 *
 *   npm run db:sql
 *
 * This exists because applying migrations needs either the Supabase CLI (which
 * wants an access token and the database password) or the dashboard. The dashboard
 * costs one paste and shares no extra credentials, so it wins for a first setup.
 *
 * The whole bundle runs inside a single transaction: if any statement fails, the
 * database is left exactly as it was rather than half-migrated.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const MIGRATIONS_DIR = join(ROOT, 'supabase', 'migrations')
const OUT_FILE = join(ROOT, 'supabase', 'bundle.sql')

const files = readdirSync(MIGRATIONS_DIR)
  .filter((file) => file.endsWith('.sql'))
  .sort()

const bundle = [
  '-- Generated by `npm run db:sql`. Do not edit; edit the migrations instead.',
  '--',
  '-- Paste this whole file into the Supabase SQL editor and run it once.',
  '-- It is wrapped in a transaction, so a failure leaves nothing behind.',
  '',
  'begin;',
  '',
  ...files.flatMap((file) => [
    `-- ${'='.repeat(74)}`,
    `-- ${file}`,
    `-- ${'='.repeat(74)}`,
    '',
    readFileSync(join(MIGRATIONS_DIR, file), 'utf8').trimEnd(),
    '',
  ]),
  'commit;',
  '',
].join('\n')

writeFileSync(OUT_FILE, bundle, 'utf8')

console.log(`Bundled ${files.length} migrations into ${relative(ROOT, OUT_FILE)}`)
for (const file of files) console.log(`  ${file}`)
console.log(
  '\nPaste it into https://supabase.com/dashboard/project/_/sql/new and run it once.\n',
)
