/**
 * Seeds the twelve starter questions and their placeholder screenshots.
 *
 *   npm run db:seed -- --dry-run   validate everything, write the SVGs to disk,
 *                                  regenerate the shot list. No network.
 *   npm run db:seed                the above, plus upload to Storage and upsert
 *                                  the questions through save_question_version.
 *
 * Idempotent: question ids and image keys are derived from each question's slug,
 * so running it twice updates rather than duplicates.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { createClient } from '@supabase/supabase-js'

import { SHOTS_BUCKET, readSupabaseEnv } from '@/lib/supabase/env'
import { buildSeedQuestions, placeholderSvg, rpcPayload } from './seed-build'

const DRY_RUN = process.argv.includes('--dry-run')
const ROOT = join(import.meta.dirname, '..')
const LOCAL_SHOTS_DIR = join(ROOT, 'public', 'seed-shots')
const SHOT_LIST = join(ROOT, 'content', 'seed-shot-list.md')

console.log(`\nBuilding the seed${DRY_RUN ? ' (dry run)' : ''}\n`)

let built
try {
  built = buildSeedQuestions()
} catch (error) {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
}

console.log(`  ok  all ${built.length} questions pass the schema and name real components`)

const allShots = built.flatMap((item) => item.shots)
console.log(`  ok  ${allShots.length} placeholder screenshots to generate`)

// --- write the SVGs locally so they can be eyeballed ------------------------

mkdirSync(LOCAL_SHOTS_DIR, { recursive: true })
for (const shot of allShots) {
  writeFileSync(join(LOCAL_SHOTS_DIR, shot.key), placeholderSvg(shot.key, shot.description), 'utf8')
}
console.log('  ok  wrote them to public/seed-shots/')

// --- the shot list: what to capture, and under which key --------------------

writeFileSync(
  SHOT_LIST,
  [
    '# Seed shot list',
    '',
    'Generated by `npm run db:seed`. Every seeded question points at a placeholder.',
    'To replace one with a real capture, upload it through the admin form — the',
    'uploader assigns a fresh opaque key and repoints the question, so nothing here',
    'needs editing by hand.',
    '',
    'The keys below only matter if you would rather overwrite a placeholder in place',
    'in Supabase Storage.',
    '',
    ...built.flatMap(({ seed, shots }) => [
      `## ${seed.slug} — ${seed.mode} · ${seed.difficulty} · ${seed.component}`,
      '',
      `> ${seed.prompt}`,
      '',
      ...shots.map((shot) => `- \`${shot.key}\` — ${shot.description}`),
      '',
    ]),
  ].join('\n'),
  'utf8',
)
console.log('  ok  wrote content/seed-shot-list.md')

if (DRY_RUN) {
  console.log('\nDry run: nothing was written to Supabase.\n')
  process.exit(0)
}

// --- upload and upsert ------------------------------------------------------

const { url, secretKey } = readSupabaseEnv()
const supabase = createClient(url, secretKey, {
  auth: { persistSession: false, autoRefreshToken: false },
})

console.log('\nUploading placeholders to Supabase Storage')
for (const shot of allShots) {
  const { error } = await supabase.storage
    .from(SHOTS_BUCKET)
    .upload(shot.key, placeholderSvg(shot.key, shot.description), {
      contentType: 'image/svg+xml',
      upsert: true,
    })
  if (error) {
    console.error(`  failed on ${shot.key}: ${error.message}`)
    process.exit(1)
  }
}
console.log(`  ok  ${allShots.length} uploaded`)

console.log('\nUpserting questions')
for (const { seed, question } of built) {
  const { error } = await supabase.rpc('save_question_version', { payload: rpcPayload(question) })
  if (error) {
    console.error(`  failed on ${seed.slug}: ${error.message}`)
    process.exit(1)
  }
  console.log(`  ok  ${seed.slug.padEnd(32)} ${seed.mode.padEnd(21)} ${seed.difficulty}`)
}

console.log(`\nSeeded ${built.length} questions and ${allShots.length} placeholders.\n`)
